module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
    colors: {
      greenA: "#799C8C",
      greenB: "#485C52",
      greenC: "#ABDBC5",
      greenD: "#B4E8D0",
      greenE: "#97C2AE",
      white: "#ffffff",
      red: "#ff0000",
      "red-light": "#ff4a4a",
      blue: "#1fb6ff",
      "blue-light": "#99e1f0",
      purple: "#7e5bef",
      pink: "#ff49db",
      "pink-light": "#ff94ea",
      orange: "#ff7849",
      green: "#13ce66",
      yellow: "#ffc82c",
      "gray-dark": "#273444",
      gray: "#8492a6",
      "gray-light": "#d3dce6",
    },
  },
  plugins: [],
};
